[workspace]
members = ["crates/source_lock"]
resolver = "3"

[workspace.package]
version = "0.1.0-alpha"
edition = "2024"
rust-version = "1.97.1"
license = "GPL-3.0-or-later"
repository = "https://github.com/radrootslabs/tera"
homepage = "https://radroots.org"
authors = ["Tyson Lupul <tyson@radroots.org>"]

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"
unimplemented = "deny"

[workspace.dependencies]
radroots_mobile_ffi = { git = "https://github.com/radrootslabs/lib", rev = "ad17b7d3455a7147cfa303d976fc5c70c3a4c0cb", version = "=0.1.0-alpha" }
