// swift-tools-version: 6.0

import PackageDescription

let package = Package(
  name: "tera",
  defaultLocalization: "en",
  platforms: [
    .iOS(.v18),
  ],
  products: [
    .library(name: "TeraApp", targets: ["TeraApp"]),
  ],
  dependencies: [
    .package(
      url: "https://github.com/radrootslabs/apple_kit.git",
      revision: "68135576af9ac34126195178dabe82f02ff69497"
    ),
  ],
  targets: [
    .binaryTarget(
      name: "TeraFFI",
      path: "Tera/Frameworks/TeraFFI.xcframework"
    ),
    .target(
      name: "TeraKitBindings",
      dependencies: ["TeraFFI"],
      path: "Tera/Generated",
      swiftSettings: [
        .swiftLanguageMode(.v5),
      ]
    ),
    .target(
      name: "TeraApp",
      dependencies: [
        "TeraKitBindings",
        .product(name: "RadrootsKit", package: "apple_kit"),
      ],
      path: "Tera",
      exclude: [
        "App/App.swift",
        "Config",
        "Frameworks",
        "Generated",
        "Info.plist",
        "tera.xcconfig",
      ],
      sources: [
        "App/AppEntry.swift",
        "App/TeraAppDelegate.swift",
        "App/TeraAppModel.swift",
        "App/TeraProductStores.swift",
        "App/TeraProvider.swift",
        "App/TeraRemoteQualification.swift",
        "App/TeraRemoteQualificationEvidence.swift",
        "App/TeraRootShell.swift",
        "App/TeraTodayNavigation.swift",
        "Runtime/TeraNativeUploadReconciliation.swift",
        "Runtime/TeraStoppedUploadRecovery.swift",
        "Runtime/TeraPublicationEvidence.swift",
        "Runtime/TeraPublicationStage.swift",
        "Runtime/TeraPublicationTargets.swift",
        "Runtime/TeraPublicationRetry.swift",
        "Runtime/TeraBackgroundUploadWaiter.swift",
        "Runtime/TeraNativeUploadExecution.swift",
        "Runtime/TeraGeneratedRuntimeBackendSubmission.swift",
        "Runtime/TeraGeneratedSubmissionOperation.swift",
        "Runtime/TeraNativeTransferJob.swift",
        "Runtime/TeraRecoveryInventory.swift",
        "Runtime/TeraRestoreRecovery.swift",
        "Runtime/TeraGeneratedRestoreRecovery.swift",
        "State/TeraRestoreRecoveryStore.swift",
        "Views/TeraRestoreRecoverySection.swift",
        "Runtime/TeraRecoveryCompletion.swift",
        "Runtime/TeraGeneratedRecoveryCompletion.swift",
        "Runtime/TeraGeneratedRecoveryInventory.swift",
        "Runtime/TeraNativeRecoveryInventory.swift",
        "Runtime/TeraNativeRecoveryStatus.swift",
        "Runtime/TeraNativeRecoverySchedule.swift",
        "Runtime/TeraGeneratedRecoveryStatus.swift",
        "State/TeraNativeRepairStore.swift",
        "Views/TeraNativeRepairView.swift",
        "Runtime/TeraRuntimeClientSubmission.swift",
        "Runtime/TeraSubmissionOperationModels.swift",
        "Runtime/TeraAddMediaCoordinator.swift",
        "Runtime/TeraUploadRenewal.swift",
        "Runtime/TeraMediaCleanup.swift",
        "Runtime/TeraMediaProcessUse.swift",
        "Runtime/TeraRemoteQualificationMediaPicker.swift",
        "Runtime/TeraDiagnosticsStore.swift",
        "Runtime/TeraGeneratedRuntimeStartup.swift",
        "Runtime/TeraBackupRuntimeStartup.swift",
        "Runtime/TeraBackupFiles.swift",
        "Runtime/TeraLocalBackupHost.swift",
        "Runtime/TeraLocalRestoreHost.swift",
        "Runtime/TeraRestoreFiles.swift",
        "Runtime/TeraBackgroundUploadRequest.swift",
        "Runtime/TeraCalendarTiming.swift",
        "Runtime/TeraCalendarPresentation.swift",
        "Runtime/TeraCalendarEditing.swift",
        "Runtime/TeraCivilDateInput.swift",
        "Runtime/TeraFoodDecimalEntry.swift",
        "Runtime/TeraCivilDateFormat.swift",
        "Runtime/TeraCheckedTime.swift",
        "Runtime/TeraComposerModels.swift",
        "Runtime/TeraDraftInventoryModels.swift",
        "Runtime/TeraDurableMediaRoots.swift",
        "Runtime/TeraComposerMediaOwnership.swift",
        "Runtime/TeraErrorRecovery.swift",
        "Runtime/TeraGeneratedCalendarCards.swift",
        "Runtime/TeraGeneratedRevisionSource.swift",
        "Runtime/TeraRevisionModels.swift",
        "Runtime/TeraDraftStatus.swift",
        "Runtime/TeraGeneratedDraftStatus.swift",
        "Runtime/TeraGeneratedRevisionStatus.swift",
        "State/TeraRevisionDetailStore.swift",
        "Views/TeraRevisionDetailView.swift",
        "Runtime/TeraRevisionRuntimeClient.swift",
        "Runtime/TeraGeneratedComposer.swift",
        "Runtime/TeraGeneratedDraftInventory.swift",
        "Runtime/TeraGeneratedHostSigner.swift",
        "Runtime/TeraGeneratedRuntimeBackend.swift",
        "Runtime/TeraGeneratedRuntimeBackendComposer.swift",
        "Runtime/TeraGeneratedSubmission.swift",
        "Runtime/TeraGeneratedRuntimeFailure.swift",
        "Runtime/TeraGeneratedTodayPage.swift",
        "Runtime/TeraGeneratedTodayReads.swift",
        "Runtime/TeraViewerCalendarContext.swift",
        "Runtime/TeraGeneratedTodaySync.swift",
        "Runtime/TeraLifecycleCoordinator.swift",
        "Runtime/TeraLifecycleBridge.swift",
        "Runtime/TeraOpenedMedia.swift",
        "Runtime/TeraPreparedMediaHandle.swift",
        "Runtime/TeraRuntimeBoundedTask.swift",
        "Runtime/TeraRuntimeBackend.swift",
        "Runtime/TeraRuntimeClient.swift",
        "Runtime/TeraRuntimeFailureMapping.swift",
        "Runtime/TeraRuntimeClientComposer.swift",
        "Runtime/TeraRuntimeClientDraftInventory.swift",
        "Runtime/TeraRuntimeTodayClient.swift",
        "Runtime/TeraRuntimeModels.swift",
        "Runtime/TeraTodaySyncModels.swift",
        "Runtime/TeraTodayPageModels.swift",
        "Runtime/TeraRuntimeInvalidation.swift",
        "Runtime/TeraGeneratedInvalidation.swift",
        "Runtime/TeraRuntimeResourceCreation.swift",
        "Runtime/TeraRuntimeResourceTask.swift",
        "Runtime/TeraRuntimeShutdownTask.swift",
        "Runtime/TeraSessionGeneration.swift",
        "Runtime/TeraSubmissionModels.swift",
        "Runtime/TeraUserMessageClassifier.swift",
        "Runtime/TeraUserMessages.swift",
        "State/TeraLegacySubmission.swift",
        "State/TeraSubmissionEffects.swift",
        "State/TeraSubmissionInventory.swift",
        "State/TeraSubmissionStore.swift",
        "State/TeraSubmissionStopControl.swift",
        "State/TeraAddStore.swift",
        "State/TeraAddSelectionActions.swift",
        "State/TeraAddAffordances.swift",
        "State/TeraPublicationActions.swift",
        "State/TeraRevisionPreparation.swift",
        "State/TeraAddCardIntents.swift",
        "State/TeraEditingProtection.swift",
        "State/TeraAddUploadCompletion.swift",
        "State/TeraComposerAutosave.swift",
        "State/TeraComposerSaveState.swift",
        "State/TeraDraftRecoveryStore.swift",
        "State/TeraTodayRelayPresentation.swift",
        "State/TeraTodayDiscoveryPresentation.swift",
        "State/TeraAddStartupSnapshot.swift",
        "State/TeraAddPresentation.swift",
        "State/TeraStoreObservation.swift",
        "State/TeraConfigurationStore.swift",
        "State/TeraIdentityStore.swift",
        "State/TeraMediaStore.swift",
        "State/TeraMediaPresentationLimits.swift",
        "State/TeraMediaWorkQueue.swift",
        "State/TeraMediaThumbnail.swift",
        "State/TeraSessionStore.swift",
        "State/TeraSessionBootstrap.swift",
        "State/TeraSupportingStores.swift",
        "State/TeraSettingsStore.swift",
        "State/TeraTodayStore.swift",
        "State/TeraTodayReconciler.swift",
        "State/TeraTodayReconciliationTask.swift",
        "State/TeraTodayPresentation.swift",
        "Views/TeraAddSubmitButton.swift",
        "Views/TeraSubmissionViews.swift",
        "Views/TeraPublicationTargetsView.swift",
        "Views/TeraAddView.swift",
        "Views/TeraAddSaveStatus.swift",
        "Views/TeraDraftsSheet.swift",
        "Views/TeraEditingProtectionActions.swift",
        "Views/TeraEditingProtectionUITestSurface.swift",
        "Views/TeraRecoveryUITestSurface.swift",
        "Views/TeraSupportingViews.swift",
        "Views/TeraContextPicker.swift",
        "Views/TeraTodayDiscoveryView.swift",
        "Views/TeraTodayView.swift",
        "Views/TeraTodayCurrentDetail.swift",
        "Views/TeraTodayDetailView.swift",
        "Views/TeraTodayCardPresentation.swift",
        "Views/TeraCalendarMetadata.swift",
        "Views/TeraCalendarComposerFields.swift",
        "Views/TeraCivilDateField.swift",
        "Views/TeraTimedCalendarField.swift",
        "Views/TeraTodayStatusView.swift",
        "Views/TeraTodayPagingStatusView.swift",
        "Views/RuntimeStatusView.swift",
      ],
      resources: [
        .process("Resources/PrivacyInfo.xcprivacy"),
        .process("Resources/en.lproj/Localizable.strings"),
      ]
    ),
    .testTarget(
      name: "TeraAppTests",
      dependencies: ["TeraApp"],
      path: "TeraTests"
    ),
    .testTarget(
      name: "TeraAppPublicAPITests",
      dependencies: ["TeraApp"],
      path: "TeraPublicAPITests"
    ),
  ],
  swiftLanguageModes: [.v6]
)
