[package]
name = "radroots_app_wasm"
description = "WebAssembly bindings for Radroots web apps"
version.workspace = true
edition.workspace = true
authors = ["Radroots Authors"]
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
radroots_app_core = { workspace = true, default-features = false }
wasm-bindgen = { workspace = true }
